In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

X_data = torch.Tensor([
    [1,2],[2,3],[3,1],[4,3],[5,3],[6,2]])
Y_data = torch.Tensor([[0],
    [0],
    [0],
    [1],
    [1],
    [1],])
Weight = torch.zeros((2,1), requires_grad = True)
Bias = torch.zeros(1, requires_grad = True)

hypo = 1 / (1 + torch.exp(-(torch.mm(X_data,Weight) + Bias)))
print(hypo)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)


In [22]:
hypothesis = torch.sigmoid(torch.mm(X_data,Weight)+Bias)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)


In [23]:
print(F.binary_cross_entropy(hypothesis,Y_data))

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)


In [24]:
losses = -Y_data*torch.log(hypothesis) + (1-Y_data) * torch.log(1- hypothesis)
print(losses)

tensor([[-0.6931],
        [-0.6931],
        [-0.6931],
        [ 0.6931],
        [ 0.6931],
        [ 0.6931]], grad_fn=<AddBackward0>)


In [25]:
optimizer = optim.SGD([Weight, Bias], lr=0.1)

In [26]:
for epoch in range(1001):
    hypothesis_ = torch.sigmoid(torch.mm(X_data,Weight)+Bias)
    cost  = F.binary_cross_entropy(hypothesis_, Y_data)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0 :
        print("Epoch : {}, Loss : {:.6f}".format(epoch,cost.item()))
        
        
x_test = torch.Tensor(
    [[2,5]])
print(torch.sigmoid(torch.mm(x_test,Weight)+Bias))


Epoch : 0, Loss : 0.693147
Epoch : 100, Loss : 0.414327
Epoch : 200, Loss : 0.349521
Epoch : 300, Loss : 0.301302
Epoch : 400, Loss : 0.263532
Epoch : 500, Loss : 0.233518
Epoch : 600, Loss : 0.209313
Epoch : 700, Loss : 0.189496
Epoch : 800, Loss : 0.173035
Epoch : 900, Loss : 0.159179
Epoch : 1000, Loss : 0.147375
tensor([[0.2638]], grad_fn=<SigmoidBackward>)


In [34]:
class Logistic_Regression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,X_data):
        return self.sigmoid(self.linear(X_data))
    
Lr_Model = Logistic_Regression()
optimizer2 = optim.SGD(Lr_Model.parameters(),lr =0.01)

In [ ]:
for Epoch in range(101):
    hypothesis__ = Lr_Model(X_data)
    cost = F.binary_cross_entropy(hypothesis__,Y_data)
    