# Numpy for Finance 02 - 슬라이싱과 인덱싱

<img width="320" src="http://i.imgur.com/1Z9bz5V.jpg">


### 2018 FinanceData.KR

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (14,4)
plt.rcParams["axes.grid"] = True

# 인덱싱 (행, 열)

In [2]:
import numpy as np

ar = np.array( [[10, 20, 30], [60, 70, 80], [90, 91, 92]] )

print (ar[1][2]) # 80
print (ar[1,2]) # 80 동일
print (ar[1,1]) # ar[1][1] 동일

80
80
70


# 마이너스 인덱스

```python
ar[-2] # 끝에서 2번째 행
ar[-2:] # 마지막 2개 행
ar[:-2] # 마지막 2개 행을 제외한 모든 행
```

In [3]:
ar = np.arange(0,16).reshape((4,4))

print (ar)
print ('~' * 40)
print (ar[-2])
print ('~' * 40)
print (ar[-2:] )
print ('~' * 40)
print (ar[:-2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 8  9 10 11]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 8  9 10 11]
 [12 13 14 15]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0 1 2 3]
 [4 5 6 7]]


# 슬라이싱
특정 영역을 지정하거나 잘라낸다


In [4]:
ar = np.arange(0,16).reshape((4,4))

print (ar)
print ('~' * 40)
print (ar[0])
print ('~' * 40)
print (ar[1,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0 1 2 3]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5


In [5]:
print (ar)
print ('~' * 40)

ar[2, :2] = 99 # 값 바꾸기
print (ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 0  1  2  3]
 [ 4  5  6  7]
 [99 99 10 11]
 [12 13 14 15]]


# 슬라이싱 slicing

<img width="80%" src="http://i.imgur.com/AAYMAEO.png" >

# 다양한 슬라이싱

```python
ar = np.arange(0,16).reshape((4,4))

ar[:]         # ar의 모든  row (= ar)
ar[0]        # row 0
ar[1]        # row 1
ar[:,1]      # col 1
ar[1:]       # row 1 이후, ar[1:,] 혹은 ar[1:,:] 와 동일한 표현
ar[:2]       # row 0~1
ar[:2,1:]   # row 0~1, col 1 이후 
ar[:2,:2]   # row 0~1, col 0~1
ar[2,:2]    # row 2, col 0~1
ar[:,2]      # col 2
ar[:,1:3]   # col 1~2
```

# ndarry 연산
ndarray 간에 혹은 ndarray와 단일값 사이에 사칙연산(+, -, , /, * ) 이 가능
* ndarray 연산자 ndarray
* value 연산자 ndarray



# 연산 (브로드캐스팅)
크기가 다른 ndarray 간의 연산을 브로드캐스팅 이라고 한다

<img width="40%" src="https://i.imgur.com/lxuY7cr.png" >

In [6]:
ar = np.array([[0, 1, 2], [10, 11, 12], [20, 21, 22], [30, 31, 32]])
print (ar)
print ('~' * 40)

p = ar * 10
print (p)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[  0  10  20]
 [100 110 120]
 [200 210 220]
 [300 310 320]]


# 연산 (브로드캐스팅)

<img width="80%" src="http://i.imgur.com/Rj1ML5O.jpg" >


In [7]:
ar = np.array([[0, 1, 2], [10, 11, 12], [20, 21, 22], [30, 31, 32]])
print (ar)

print ('~' * 40)
p = ar + np.array([[0, 1, 2]])
print (p)

print ('~' * 40)
p = ar + np.array([[0], [1], [2], [3]])
print (p)

print ('~' * 40)
p = np.array([[0], [10], [20], [30]]) + np.array([[0, 1, 2]])
print (p)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 0  2  4]
 [10 12 14]
 [20 22 24]
 [30 32 34]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 0  1  2]
 [11 12 13]
 [22 23 24]
 [33 34 35]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# 슬라이싱과 연산
* ar[n:m] = 20 선택 영역에 브로드캐스팅
* 리스트의 슬라이싱과 차이점은 원본 ndarray에 대한 뷰라는 점
* 뷰에 대한 조작은 그대로 원본에 반영 (별도의 ndarray가 생성되지 않는다)

# 슬라이싱 예제

In [8]:
ar = np.zeros((5,5))
v = ar[1:-1,1:-1]
v[:] = 1
print(ar)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 다양한 슬라이싱

<img width="80%" src="http://i.imgur.com/KCnnlMh.png">

In [9]:
ar = np.array([[0], [10], [20], [30], [40], [50]]) + np.array([[0, 1, 2, 3, 4, 5]])
print(ar)

print ('~' * 40)
p = ar[0, 1:3]
print(p)

print ('~' * 40)
p = ar[:, 3]
print(p)


print ('~' * 40)
p = ar[4:, 4:]
print(p)

print ('~' * 40)
p = ar[2::2, ::2]
print(p)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1 2]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 3 13 23 33 43 53]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[44 45]
 [54 55]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[20 22 24]
 [40 42 44]]


# View & Copy

슬라이싱의 결과는 뷰(view)이다. 뷰를 통해 수정하면 원본 데이터가 수정된다.

In [10]:
ar = np.array([[10, 20, 30], [60, 70, 80], [90, 91, 92]])
v = ar[1]
v[:] = 50 # v 배열 전체 요소에 20을 할당

#  v는 ar의 뷰, v의 값을 변경하는 것은 ar의 값을 변경
print(ar)

[[10 20 30]
 [50 50 50]
 [90 91 92]]


In [11]:
# ar과 v를 완전히 다른 객체로 만드려면 copy를 사용

ar = np.array([[10, 20, 30], [60, 70, 80], [90, 91, 92]])
v = ar[1].copy()
v[:] = 50 # v 배열 전체 요소에 20을 할당

#  v는 ar의 뷰, v의 값을 변경하는 것은 ar의 값을 변경
print(ar)

[[10 20 30]
 [60 70 80]
 [90 91 92]]


In [12]:
v

array([50, 50, 50])

# 불리언 인덱싱 (Boolean indexing)

In [13]:
city = np.array(['newyork', 'seoul', 'shanghai', 'tokyo', 'london'])
val = np.array([10, 20, 30, 40, 50])

city == 'seoul'         # array([False, True, False, False, False], dtype=bool)
val[city == 'seoul']   # array([20])
city[val >= 30]         # array(['shanghai', 'tokyo', 'london'], dtype='<U8')
city[city != 'tokyo']    # array(['newyork', 'seoul', 'shanghai', 'london']

mask = (city == 'shanghai') | (city == 'london')
val[mask]                # array([30, 50])

array([30, 50])

# 불리언 인덱싱 (필터링)

In [14]:
# 0 이하를 모두 0으로 만들기
x = np.array([-2, 0, 4, 6, -8, 5, 9, 2])
x[x < 0] = 0 

x

array([0, 0, 4, 6, 0, 5, 9, 2])

# 팬시 인덱싱 (fancy indexing)
* 정수 리스트(혹은 배열)를 이용하여 여러 개를 동시에 선택
* 팬시 인덱싱은 복사가 일어난다.
* ar[[3,4,5,2,0]] # 지정된 행을 순서대로 추출

In [15]:
ar = np.array([[0], [10], [20], [30], [40], [50]]) + np.array([[0, 1, 2, 3, 4, 5]])
ar

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [16]:
ar[[0, 2, -1]]   # 지정한 row 얻기

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25],
       [50, 51, 52, 53, 54, 55]])

In [17]:
ar[:, [0, 2, -1]]  # 지정한 column 얻기

array([[ 0,  2,  5],
       [10, 12, 15],
       [20, 22, 25],
       [30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

# 리뷰
* 슬라이싱 slicing
* 불리언 인덱싱 (필터링) x[x < 0]
* 팬시 인덱싱 ar[[0, 2, -1]]  

----
### 2018 FinanceData http://fb.com/financedata http://financedata.github.com