In [8]:
import numpy
import torch

In [20]:
t =torch.FloatTensor([[1,2,3],[4,5,6]])


In [21]:
print(t[4:-1])
print(t[-1])
print(t.shape)

tensor([])
tensor([4., 5., 6.])
torch.Size([2, 3])


In [22]:
print(t.size())

torch.Size([2, 3])


In [23]:
print(t.dim())

2


In [33]:
t_2 = torch.Tensor([
    [1,2,3],
    [4,5,6],
    
    [7,8,9],
    [10,11,12]   
])
print(t_2)
print(t_2[:,1]) # 1열 출력

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([ 2.,  5.,  8., 11.])


In [28]:
print(t_2.dim() , t_2.shape , t_2.size())

2 torch.Size([4, 3]) torch.Size([4, 3])


In [67]:
m1 = torch.Tensor([[100,200]]).t()
m2 = torch.Tensor([[3],[4]]).t()
print(m1+m2)
print(m1.shape)
print(m2.shape)
m3 = torch.mm(m1,m2)

tensor([[103., 104.],
        [203., 204.]])
torch.Size([2, 1])
torch.Size([1, 2])


In [71]:
print(m3.mean(dim=1))
print(m3.mean(dim=0))
print(m3.mean())

tensor([350., 700.])
tensor([450., 600.])
tensor(525.)


In [102]:
t = torch.Tensor([[1,2],[3,4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [86]:
#max 실습 
#max는 가장큰 element의 index를 반환한다.
t = torch.Tensor([
    [1,2,3],
    [5,10,7],
    [10,20,30]
])
print(t.max())
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])
print(t.max(dim=1))
print(t.max(dim=0))
print(t.max(dim=-1))

tensor(30.)
tensor([10., 20., 30.])
tensor([2, 2, 2])
(tensor([ 3., 10., 30.]), tensor([2, 1, 2]))
(tensor([10., 20., 30.]), tensor([2, 2, 2]))
(tensor([ 3., 10., 30.]), tensor([2, 1, 2]))


In [87]:
ft = torch.Tensor([
    
    [[0,2,4],
     [3,6,9]],
    [[7,8,9],
    [10,20,30]]
                ])
print(ft.shape)

torch.Size([2, 2, 3])


In [93]:
print(ft.view([4,3]))
print(ft.view([4,3]).shape)

tensor([[ 0.,  2.,  4.],
        [ 3.,  6.,  9.],
        [ 7.,  8.,  9.],
        [10., 20., 30.]])
torch.Size([4, 3])


In [100]:
print(ft.view([-1,2,2]))

tensor([[[ 0.,  2.],
         [ 4.,  3.]],

        [[ 6.,  9.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [20., 30.]]])


In [103]:
ft = torch.Tensor([[0],[1],[2]])
print(ft)

tensor([[0.],
        [1.],
        [2.]])


In [104]:
print(ft.shape)

torch.Size([3, 1])


In [105]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [107]:
print(ft.squeeze(0))

tensor([[0.],
        [1.],
        [2.]])


In [117]:
print(ft.squeeze(-2))

tensor([[0.],
        [1.],
        [2.]])


In [116]:
print(ft.unsqueeze(0))

tensor([[[0.],
         [1.],
         [2.]]])


In [119]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [122]:
x = torch.Tensor([[1,2], [3,4]])
y = torch.Tensor([[5,6], [7,8]])
print(torch.cat([x,y], dim = 0))
print(torch.cat([x,y], dim = 1)) # col이 증가하는 방향 ->

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [127]:
z = torch.Tensor([6,7])
x = torch.Tensor([1,2])
y = torch.Tensor([3,4])
print(torch.stack([x,y,z], dim = 1).size())
print(torch.stack([x,y,z], dim = 0).size())

torch.Size([2, 3])
torch.Size([3, 2])


In [128]:
temp = torch.Tensor([[1,2,3],[1,2,3]])

In [129]:
print(torch.zeros_like(temp))
print(torch.ones_like(temp))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [133]:
print(temp.mul(2))

tensor([[2., 4., 6.],
        [2., 4., 6.]])


In [134]:
print(temp)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [135]:
print(temp.mul_(2))


tensor([[2., 4., 6.],
        [2., 4., 6.]])


In [136]:
print(temp)

tensor([[2., 4., 6.],
        [2., 4., 6.]])


In [145]:
print(temp)
print(temp.shape)
print(temp.t().shape)


print(temp.matmul(temp.t()))



tensor([[2., 4., 6.],
        [2., 4., 6.]])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[56., 56.],
        [56., 56.]])
