In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as function
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

import pandas as pd

In [3]:
wine =load_wine()

In [63]:
pd.DataFrame(wine.data , columns=wine.feature_names)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [64]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [65]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [4]:
wine_data = wine.data
wine_target = wine.target
train_X,test_X,train_Y,test_Y = train_test_split(wine_data,wine_target,test_size = 0.2 )
print(len(train_X),len(train_Y))
print(len(test_X),len(test_Y))

142 142
36 36


In [5]:
train_X = torch.from_numpy(train_X).float()
train_Y = torch.from_numpy(train_Y).long()

test_X = torch.from_numpy(test_X).float()
test_Y = torch.from_numpy(test_Y).long()
train_X = train_X[:len(train_X)]
test_X = train_X[:len(test_X)]

print(test_X.shape)
print(test_Y.shape)
print(train_X.shape)
print(train_Y.shape)

torch.Size([36, 13])
torch.Size([36])
torch.Size([142, 13])
torch.Size([142])


In [6]:
train = TensorDataset(train_X, train_Y)

train_loader = DataLoader(train,batch_size=16,shuffle=True)


In [10]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(13,96)
        self.fc2 = nn.Linear(96,3)
    def forward(self, x):
        x= function.relu(self.fc1(x))
       
        x =self.fc2(x)
        return function.softmax(x)
model = Net()

In [11]:
print(model)

Net(
  (fc1): Linear(in_features=13, out_features=96, bias=True)
  (fc2): Linear(in_features=96, out_features=3, bias=True)
)


In [12]:

criterion =nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(),lr = 0.01)
for epoch in range(300):
    total_loss= 0
    for train_X,train_Y in train_loader:
        train_X,train_Y = Variable(train_X), Variable(train_Y)
        optimizer.zero_grad()
        output = model(train_X)
        loss = criterion(output,train_Y)
        loss.backward()
        optimizer.step()
        total_loss += loss.data[0]
    if(epoch+1) % 50 == 0:
         print(epoch+1, total_loss)

C:\Anaconda3\envs\pytlesson\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.
C:\Anaconda3\envs\pytlesson\lib\site-packages\ipykernel_launcher.py:12: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  if sys.path[0] == '':


50 tensor(11.6862)
100 tensor(11.6951)
150 tensor(10.7934)
200 tensor(10.7844)
250 tensor(10.8023)
300 tensor(10.7844)


In [13]:
test_X,test_Y = Variable(test_X),Variable(test_Y)
print(test_X)
result = torch.max(model(test_X).data,1)[1]
print(torch.max(model(test_X).data, 1))
#print(model(test_X).data)
accuracy = sum(test_Y.data.numpy()==result.numpy()) / len(test_Y.data.numpy())
print(result.numpy())
print(test_Y.data.numpy())
# 모델에서 나온것과 result가 일치하는 개수를 구한다.
print(accuracy)

tensor([[  13.8200,    1.7500,    2.4200,   14.0000,  111.0000,    3.8800,
            3.7400,    0.3200,    1.8700,    7.0500,    1.0100,    3.2600,
         1190.0000],
        [  13.6700,    1.2500,    1.9200,   18.0000,   94.0000,    2.1000,
            1.7900,    0.3200,    0.7300,    3.8000,    1.2300,    2.4600,
          630.0000],
        [  14.1000,    2.0200,    2.4000,   18.8000,  103.0000,    2.7500,
            2.9200,    0.3200,    2.3800,    6.2000,    1.0700,    2.7500,
         1060.0000],
        [  13.8600,    1.5100,    2.6700,   25.0000,   86.0000,    2.9500,
            2.8600,    0.2100,    1.8700,    3.3800,    1.3600,    3.1600,
          410.0000],
        [  12.6900,    1.5300,    2.2600,   20.7000,   80.0000,    1.3800,
            1.4600,    0.5800,    1.6200,    3.0500,    0.9600,    2.0600,
          495.0000],
        [  11.8200,    1.4700,    1.9900,   20.8000,   86.0000,    1.9800,
            1.6000,    0.3000,    1.5300,    1.9500,    0.9500,    3.3

C:\Anaconda3\envs\pytlesson\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  # Remove the CWD from sys.path while we load stuff.
